sectors = {
    "Energy": {
        "XOM": "Exxon Mobil",
        "CVX": "Chevron",
        "COP": "ConocoPhillips",
        "EOG": "EOG Resources",
        "SLB": "Schlumberger",
        "KMI": "Kinder Morgan",
        "OKE": "ONEOK",
        "ET": "Energy Transfer",
        "WMB": "Williams Companies",
        "MPC": "Marathon Petroleum",
        "PSX": "Phillips 66",
        "VLO": "Valero Energy",
        "HES": "Hess",
        "OXY": "Occidental Petroleum",
        "PXD": "Pioneer Natural Resources",
        "HAL": "Halliburton",
        "BKR": "Baker Hughes",
        "DVN": "Devon Energy",
        "APA": "APA Corporation",
        "FANG": "Diamondback Energy",
        "AR": "Antero Resources",
        "RRC": "Range Resources",
        "EQT": "EQT Corporation",
        "SM": "SM Energy"
    },
    "Materials": {
        "LIN": "Linde",
        "APD": "Air Products & Chemicals",
        "ECL": "Ecolab",
        "SHW": "Sherwin-Williams",
        "DD": "DuPont de Nemours",
        "DOW": "Dow Inc.",
        "NUE": "Nucor",
        "PPG": "PPG Industries",
        "FCX": "Freeport-McMoRan",
        "CF": "CF Industries",
        "LYB": "LyondellBasell",
        "ALB": "Albemarle",
        "MLM": "Martin Marietta Materials",
        "VMC": "Vulcan Materials",
        "CE": "Celanese",
        "IFF": "International Flavors & Fragrances",
        "AVY": "Avery Dennison",
        "WRK": "WestRock",
        "PKG": "Packaging Corp of America",
        "EMN": "Eastman Chemical"
    },
    "Industrials": {
        "GE": "General Electric",
        "HON": "Honeywell",
        "UPS": "United Parcel Service",
        "BA": "Boeing",
        "LMT": "Lockheed Martin",
        "CAT": "Caterpillar",
        "RTX": "Raytheon Technologies",
        "DE": "Deere & Co.",
        "EMR": "Emerson Electric",
        "MMM": "3M Company",
        "CSX": "CSX Corp.",
        "UNP": "Union Pacific",
        "FDX": "FedEx",
        "WM": "Waste Management",
        "ITW": "Illinois Tool Works",
        "ETN": "Eaton Corp.",
        "PH": "Parker-Hannifin",
        "TDG": "TransDigm Group",
        "ROK": "Rockwell Automation",
        "CARR": "Carrier Global"
    },
    "Utilities": {
        "NEE": "NextEra Energy",
        "DUK": "Duke Energy",
        "SO": "Southern Company",
        "D": "Dominion Energy",
        "AEP": "American Electric Power",
        "EXC": "Exelon",
        "SRE": "Sempra Energy",
        "ED": "Consolidated Edison",
        "XEL": "Xcel Energy",
        "PEG": "Public Service Enterprise Group",
        "EIX": "Edison International",
        "WEC": "WEC Energy Group",
        "LNT": "Alliant Energy",
        "CMS": "CMS Energy",
        "AWK": "American Water Works",
        "PNW": "Pinnacle West Capital",
        "NRG": "NRG Energy",
        "AES": "AES Corp.",
        "NI": "NiSource",
        "OGE": "OGE Energy"
    },
    "Healthcare": {
        "JNJ": "Johnson & Johnson",
        "UNH": "UnitedHealth Group",
        "PFE": "Pfizer",
        "MRK": "Merck & Co.",
        "ABBV": "AbbVie",
        "TMO": "Thermo Fisher Scientific",
        "ABT": "Abbott Laboratories",
        "MDT": "Medtronic",
        "BMY": "Bristol-Myers Squibb",
        "AMGN": "Amgen",
        "LLY": "Eli Lilly",
        "GILD": "Gilead Sciences",
        "CVS": "CVS Health",
        "CI": "Cigna",
        "HCA": "HCA Healthcare",
        "ISRG": "Intuitive Surgical",
        "REGN": "Regeneron Pharmaceuticals",
        "ZBH": "Zimmer Biomet",
        "BSX": "Boston Scientific",
        "MCK": "McKesson"
    },
    "Financials": {
        "JPM": "JPMorgan Chase",
        "BAC": "Bank of America",
        "WFC": "Wells Fargo",
        "C": "Citigroup",
        "GS": "Goldman Sachs",
        "MS": "Morgan Stanley",
        "AXP": "American Express",
        "BRK.B": "Berkshire Hathaway",
        "BLK": "BlackRock",
        "V": "Visa",
        "MA": "Mastercard",
        "PNC": "PNC Financial Services",
        "USB": "U.S. Bancorp",
        "TFC": "Truist Financial",
        "AIG": "American International Group",
        "CME": "CME Group",
        "ICE": "Intercontinental Exchange",
        "SCHW": "Charles Schwab",
        "SPGI": "S&P Global",
        "CB": "Chubb Limited"
    },
    "Consumer Discretionary": {
        "AMZN": "Amazon",
        "TSLA": "Tesla",
        "HD": "Home Depot",
        "MCD": "McDonald's",
        "SBUX": "Starbucks",
        "NKE": "Nike",
        "LOW": "Lowe's",
        "BKNG": "Booking Holdings",
        "TJX": "TJX Companies",
        "LULU": "Lululemon Athletica",
        "GM": "General Motors",
        "F": "Ford Motor",
        "CMG": "Chipotle Mexican Grill",
        "YUM": "Yum! Brands",
        "BBY": "Best Buy",
        "ROST": "Ross Stores",
        "ORLY": "O'Reilly Automotive",
        "AZO": "AutoZone",
        "HLT": "Hilton Worldwide",
        "MAR": "Marriott International"
    },
    "Consumer Staples": {
        "WMT": "Walmart",
        "COST": "Costco",
        "PG": "Procter & Gamble",
        "KO": "Coca-Cola",
        "PEP": "PepsiCo",
        "PM": "Philip Morris International",
        "MDLZ": "Mondelez International",
        "CL": "Colgate-Palmolive",
        "KMB": "Kimberly-Clark",
        "KR": "Kroger",
        "TGT": "Target",
        "WBA": "Walgreens Boots Alliance",
        "GIS": "General Mills",
        "SJM": "J.M. Smucker",
        "HSY": "Hershey",
        "STZ": "Constellation Brands",
        "CAG": "Conagra Brands",
        "TSN": "Tyson Foods",
        "CHD": "Church & Dwight",
        "K": "Kellanova"
    },
    "Information Technology": {
        "AAPL": "Apple",
        "MSFT": "Microsoft",
        "NVDA": "NVIDIA",
        "AVGO": "Broadcom",
        "ADBE": "Adobe",
        "CRM": "Salesforce",
        "CSCO": "Cisco Systems",
        "ORCL": "Oracle",
        "INTC": "Intel",
        "AMD": "Advanced Micro Devices",
        "TXN": "Texas Instruments",
        "NOW": "ServiceNow",
        "INTU": "Intuit",
        "QCOM": "Qualcomm",
        "ADP": "Automatic Data Processing",
        "IBM": "IBM",
        "AMAT": "Applied Materials",
        "MU": "Micron Technology",
        "LRCX": "Lam Research",
        "PANW": "Palo Alto Networks"
    },
    "Communication Services": {
        "GOOGL": "Alphabet Class A",
        "GOOG": "Alphabet Class C",
        "META": "Meta Platforms",
        "NFLX": "Netflix",
        "T": "AT&T",
        "VZ": "Verizon",
        "CMCSA": "Comcast",
        "DIS": "Walt Disney",
        "CHTR": "Charter Communications",
        "TMUS": "T-Mobile US",
        "EA": "Electronic Arts",
        "TTWO": "Take-Two Interactive",
        "PARA": "Paramount Global",
        "WBD": "Warner Bros. Discovery",
        "FOX": "Fox Corp. Class B",
        "FOXA": "Fox Corp. Class A",
        "LYV": "Live Nation Entertainment",
        "SPOT": "Spotify",
        "MTCH": "Match Group",
        "BIDU": "Baidu"
    },
    "Real Estate": {
        "PLD": "Prologis",
        "AMT": "American Tower",
        "CCI": "Crown Castle",
        "EQIX": "Equinix",
        "PSA": "Public Storage",
        "O": "Realty Income",
        "SPG": "Simon Property Group",
        "WELL": "Welltower",
        "VICI": "VICI Properties",
        "DLR": "Digital Realty Trust",
        "AVB": "AvalonBay Communities",
        "EQR": "Equity Residential",
        "EXR": "Extra Space Storage",
        "SBAC": "SBA Communications",
        "INVH": "Invitation Homes",
        "UDR": "UDR Inc.",
        "ARE": "Alexandria Real Estate Equities",
        "MAA": "Mid-America Apartment Communities",
        "REG": "Regency Centers",
        "KIM": "Kimco Realty"
    }
}
